-- 1. 모든 제품의 이름과 설명을 조회하시오.
SELECT PRODUCT_NAME, DESCRIPTION FROM ERP_PRODUCT;

-- 2. 현재고가 40개 미만인 자재의 이름과 수량을 조회하시오.
SELECT MATERIAL_NAME, STOCK_QTY 
FROM ERP_MATERIAL 
WHERE STOCK_QTY < 40;

-- 3. '전기식'으로 시작하는 모든 제품을 조회하시오.
SELECT * FROM ERP_PRODUCT WHERE PRODUCT_NAME LIKE '전기식%';

-- 4. 등록된 자재 중 이름에 '펌프'가 포함된 자재 정보를 조회하시오.
SELECT * FROM ERP_MATERIAL WHERE MATERIAL_NAME LIKE '%펌프%';

-- 5. 2025년 12월 5일 이후에 생산된 생산 주문을 조회하시오.
SELECT * FROM ERP_PRODUCTION_ORDER WHERE ORDER_DATE >= TO_DATE('2025-12-05', 'YYYY-MM-DD');

-- 6. 각 제품별 현재 완제품 재고 수량을 제품명과 함께 조회하시오.
SELECT P.PRODUCT_NAME, I.STOCK_QTY
FROM ERP_PRODUCT P
JOIN ERP_INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID;

-- 7. '전기식 세척기1'을 생산하기 위해 필요한 자재 목록과 필요 수량(BOM)을 조회하시오.
SELECT M.MATERIAL_NAME, B.REQUIRED_QTY
FROM ERP_PRODUCT P
JOIN ERP_BOM B ON P.PRODUCT_ID = B.PRODUCT_ID
JOIN ERP_MATERIAL M ON B.MATERIAL_ID = M.MATERIAL_ID
WHERE P.PRODUCT_NAME = '전기식 세척기1';

--8. 생산 주문(ORDER) 내역 중, 주문된 제품의 이름과 주문 수량, 주문 일자를 조회하시오.
SELECT O.ORDER_ID, P.PRODUCT_NAME, O.ORDER_QTY, O.ORDER_DATE
FROM ERP_PRODUCTION_ORDER O
JOIN ERP_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID;

--9. 실제 생산(RECORD)이 완료된 건에 대해, 어떤 제품이 몇 개 생산되었는지 조회하시오.
SELECT R.PRODUCED_DATE, P.PRODUCT_NAME, R.PRODUCED_QTY
FROM ERP_PRODUCTION_RECORD R
JOIN ERP_PRODUCTION_ORDER O ON R.ORDER_ID = O.ORDER_ID
JOIN ERP_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID;

--10. 배송(출고) 번호 9001번에서 출고된 제품명과 수량을 조회하시오.
SELECT S.SHIPMENT_DATE, P.PRODUCT_NAME, SR.QTY
FROM ERP_SHIPMENT S
JOIN ERP_SHIPMENT_RECORD SR ON S.SHIPMENT_ID = SR.SHIPMENT_ID
JOIN ERP_PRODUCT P ON SR.PRODUCT_ID = P.PRODUCT_ID
WHERE S.SHIPMENT_ID = 9001;

--11. 각 제품별로 등록된 BOM 자재의 개수(부품 가짓수)를 구하시오.
SELECT P.PRODUCT_NAME, COUNT(B.MATERIAL_ID) AS MATERIAL_COUNT
FROM ERP_PRODUCT P
JOIN ERP_BOM B ON P.PRODUCT_ID = B.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

--12. 생산 주문(ORDER)된 제품별 총 주문 수량의 합계를 구하시오.
SELECT P.PRODUCT_NAME, SUM(O.ORDER_QTY) AS TOTAL_ORDER_QTY
FROM ERP_PRODUCTION_ORDER O
JOIN ERP_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

--13. 자재별 총 입고 횟수와 총 입고 수량을 조회하시오.
SELECT M.MATERIAL_NAME, COUNT(I.IN_ID) AS IN_COUNT, SUM(I.IN_QTY) AS TOTAL_IN_QTY
FROM ERP_MATERIAL M
JOIN ERP_MATERIAL_IN I ON M.MATERIAL_ID = I.MATERIAL_ID
GROUP BY M.MATERIAL_NAME;

--14. 일자별로 생산된 총 제품 수량을 조회하시오.
SELECT PRODUCED_DATE, SUM(PRODUCED_QTY) AS DAILY_PRODUCTION
FROM ERP_PRODUCTION_RECORD
GROUP BY PRODUCED_DATE
ORDER BY PRODUCED_DATE;

--15. 가장 재고가 많은 자재의 이름과 수량을 조회하시오. (서브쿼리 활용)
SELECT MATERIAL_NAME, STOCK_QTY
FROM ERP_MATERIAL
WHERE STOCK_QTY = (SELECT MAX(STOCK_QTY) FROM ERP_MATERIAL);

--16. '전기식 세척기1'의 제품 설명을 '2025년형 고효율 모델'로 수정하시오.
UPDATE ERP_PRODUCT
SET DESCRIPTION = '2025년형 고효율 모델'
WHERE PRODUCT_NAME = '전기식 세척기1';

--17. 자재 '전기 모터'(ID 202)의 재고가 20개 추가 입고되었다고 가정하고 재고를 수정하시오.
UPDATE ERP_MATERIAL
SET STOCK_QTY = STOCK_QTY + 20
WHERE MATERIAL_ID = 202;

--18. 생산 주문 1003번(전기식 세척기1 추가주문)의 수량을 20개에서 25개로 변경하시오.
UPDATE ERP_PRODUCTION_ORDER
SET ORDER_QTY = 25
WHERE ORDER_ID = 1003;

--19. 실수로 입력된 자재 입고 기록(IN_ID=7001)을 삭제하시오.
DELETE FROM ERP_MATERIAL_IN WHERE IN_ID = 7001;

--20. 재고가 0인 제품(현재 연료식 세척기2)을 완제품 재고 테이블에서 삭제하시오.
DELETE FROM ERP_MATERIAL_IN WHERE IN_ID = 7001;

--21. (재고 부족 확인) '전기식 세척기1' 100대를 생산하려 할 때 재고가 부족한 자재를 조회하시오.
SELECT M.MATERIAL_NAME, M.STOCK_QTY, (B.REQUIRED_QTY * 100) AS REQ_FOR_100
FROM ERP_MATERIAL M
JOIN ERP_BOM B ON M.MATERIAL_ID = B.MATERIAL_ID
WHERE B.PRODUCT_ID = 101 -- 전기식 세척기1
AND M.STOCK_QTY < (B.REQUIRED_QTY * 100);

--22. 생산 기록은 있지만 아직 출고(배송)되지 않은 제품의 총 재고 수량을 조회하시오.
SELECT P.PRODUCT_NAME, I.STOCK_QTY
FROM ERP_INVENTORY I
JOIN ERP_PRODUCT P ON I.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID NOT IN (
    SELECT PRODUCT_ID FROM ERP_SHIPMENT_RECORD
);

--23. 자재 사용 기록(USAGE)을 바탕으로, 가장 많이 사용된 자재 TOP 1을 조회하시오.
SELECT * FROM (
    SELECT M.MATERIAL_NAME, SUM(U.USED_QTY) AS TOTAL_USED
    FROM ERP_MATERIAL_USAGE U
    JOIN ERP_MATERIAL M ON U.MATERIAL_ID = M.MATERIAL_ID
    GROUP BY M.MATERIAL_NAME
    ORDER BY TOTAL_USED DESC
) WHERE ROWNUM = 1;

--24. 생산 주문량 대비 실제 생산량(달성률)을 계산하여 조회하시오.
SELECT O.ORDER_ID, O.ORDER_QTY, R.PRODUCED_QTY,
       ROUND((R.PRODUCED_QTY / O.ORDER_QTY) * 100, 2) || '%' AS ACHIVEMENT_RATE
FROM ERP_PRODUCTION_ORDER O
JOIN ERP_PRODUCTION_RECORD R ON O.ORDER_ID = R.ORDER_ID;

--25. 최근 1주일 이내에 출고된 기록이 있는 제품명을 중복 없이 조회하시오.
SELECT DISTINCT P.PRODUCT_NAME
FROM ERP_PRODUCT P
JOIN ERP_SHIPMENT_RECORD SR ON P.PRODUCT_ID = SR.PRODUCT_ID
JOIN ERP_SHIPMENT S ON SR.SHIPMENT_ID = S.SHIPMENT_ID
WHERE S.SHIPMENT_DATE >= SYSDATE - 7;

--26. 생산 주문은 들어갔으나 아직 생산되지 않은(기록이 없는) 주문 건을 조회하시오.
SELECT O.ORDER_ID, O.ORDER_DATE
FROM ERP_PRODUCTION_ORDER O
WHERE O.ORDER_ID NOT IN (SELECT ORDER_ID FROM ERP_PRODUCTION_RECORD);

--27. 제품별로 총 출고 수량을 구하고, 출고 수량이 많은 순서대로 정렬하시오.
SELECT P.PRODUCT_NAME, NVL(SUM(SR.QTY), 0) AS TOTAL_SHIPPED
FROM ERP_PRODUCT P
LEFT JOIN ERP_SHIPMENT_RECORD SR ON P.PRODUCT_ID = SR.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SHIPPED DESC;

--28. '연료식' 또는 '전기식' 제품을 주문(Order)한 내역의 총 횟수를 구하시오.
SELECT COUNT(*)
FROM ERP_PRODUCTION_ORDER O
JOIN ERP_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_NAME LIKE '%연료식%' OR P.PRODUCT_NAME LIKE '%전기식%';

--29. 자재 테이블에서 전체 평균 재고 수량보다 많이 보유하고 있는 자재들을 조회하시오.
SELECT MATERIAL_NAME, STOCK_QTY
FROM ERP_MATERIAL
WHERE STOCK_QTY > (SELECT AVG(STOCK_QTY) FROM ERP_MATERIAL);

--30. 모든 제품의 재고 현황을 '양호(5개 이상)', '부족(5개 미만)'으로 표시하여 조회하시오.
SELECT P.PRODUCT_NAME, I.STOCK_QTY,
       CASE WHEN I.STOCK_QTY >= 5 THEN '양호'
            ELSE '부족'
       END AS STATUS
FROM ERP_PRODUCT P
JOIN ERP_INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID;

